### ISSUE TITLE
no makemd implementation for exact question

### ISSUE THREAD

**Issue by skeydan** [swirldev/swirlify#39]
Hi,

I have lesson_to_html erroring out at an exact_question because there's no implementation for makemd:

(I get the error from makemd.default <- function(unit) {
  stop("No unit class specified!", unit)
}
)
Would it be possible to add an implementation for exact_question, please?

thx!

**Comment by elinw** [comment]
I have a PR https://github.com/swirldev/swirlify/pull/24  that  handles any questions types that don't exist with a simple message. There is also a PR I did specifically for images and videos.  What I do is just maintain a forked version of Swirlify that I use with the fixes from the various PRs (otherwise it's not a usable package for me since I hit those problems), pending anything getting merged in the future.  You can just install from github from your own repository.

**Comment by skeydan** [comment]
Thx for the information!
